version: "3.9"

services:
  backend:
    image: backi
    ports:
      - "8080:8080"
#    depends_on:
#      - frontend
#    env_file: env.properties
    environment:
      - localhost=host.docker.internal
    networks:
      - default
  frontend:
    image: mtt-front
    ports:
      - "5173:5173"
#    env_file: .env
    depends_on:
      - backend
    networks:
      - default

#  networks:
#    mttnetwork:
#      driver: bridge
