version: "3.9"
networks:
  kafkanetwork:
    name: my-internal-network
    external: false
services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "8080:8080"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafkanetwork
  kafka:
    image: "bitnami/kafka:latest"
    container_name: "kafka"
    ports:
      - "5173:5173"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:5173
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:5173
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:8080
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - kafkanetwork
